apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: estersilva
spec:
  type: NodePort
  selector:
    app: estersilva-playlist-recommender
  ports:
    - protocol: TCP
      port: 50008
      targetPort: 5000